# Generated by Django 3.2.25 on 2026-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='department',
            field=models.CharField(blank=True, choices=[('NUR', 'Ново-Уренгойское ЛПУМГ'), ('PURP', 'Пурпейское ЛПУМГ'), ('GUBK', 'Губкинское ЛПУМГ'), ('VING', 'Вынгапуровское ЛПУМГ'), ('ORTJ', 'Ортьягунское ЛПУМГ'), ('SRGT', 'Сургутское ЛПУМГ'), ('YBLK', 'Южно-Балыкское ЛПУМГ'), ('SAMS', 'Самсоновское ЛПУМГ'), ('DMNK', 'Демьянское ЛПУМГ'), ('TRTS', 'Туртасское ЛПУМГ'), ('TBL', 'Тобольское ЛПУМГ'), ('YARK', 'Ярковское ЛПУМГ'), ('BGND', 'Богандинское ЛПУМГ'), ('ISHM', 'Ишимское ЛПУМГ'), ('ADM', 'Администрация'), ('US', 'Управление связи'), ('UAVR', 'Управление аварийно-восстановительных работ'), ('UEZS', 'Управление по эксплуатации зданий и сооружений'), ('ITC', 'Инженерно-технический центр'), ('MSCH', 'Медико-санитарная часть'), ('UTT', 'Управление транспорта и специальной техники'), ('ALL', 'Все филиалы')], default='ALL', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='patronymic',
            field=models.CharField(blank=True, default=None, max_length=30, null=True, verbose_name='Отчетство'),
        ),
    ]
