version: '3.3'

services:
  # asterisk:
  #   image: asterisk
  #   container_name: asterisk
  #   restart: always
  #   network_mode: "host"
  #   volumes:
  #     - ./media/media/sounds:/opt/autocaller/media/sounds:ro
  #     - ./asterisk_conf:/etc/asterisk

  db:
      image: postgres
      container_name: postgres-db
      restart: always
      expose:
        - 5432
      environment:
        POSTGRES_DB: autocaller_db
        POSTGRES_USER: autocaller
        POSTGRES_PASSWORD: autocaller
      volumes:
        - ./postgres_data:/var/lib/postgresql


  redis:
    image: redis
    container_name: redis
    restart: always
    expose:
        - 6379


  nginx:
    image: nginx
    container_name: nginx
    depends_on:
      - autocaller
    restart: always
    expose:
        - 8000
    ports:
        - 80:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - static_volume:/opt/autocaller/static
      - ./media/media:/opt/autocaller/media

  autocaller:
      image: autocaller
      container_name: autocaller
      depends_on:
        - db
        - redis
      restart: always
      volumes: &app_volumes
        - ./django-files:/opt/autocaller/django-files
        - ./media:/opt/autocaller/media
        - static_volume:/opt/autocaller/static
      command: gunicorn autocaller.wsgi:application --bind 0.0.0.0:8000

  # Воркер для управления (HIPRI)
  celery-hipri:
      image: autocaller
      container_name: celery-hipri
      depends_on:
        - db
        - redis
      restart: always
      volumes: *app_volumes
      command: celery -A autocaller worker -Q hipri -l INFO --concurrency=5

  # Воркер для звонков (CELERY)
  celery-common:
      image: autocaller
      container_name: celery-common
      depends_on:
        - db
        - redis
      restart: always
      volumes: *app_volumes
      command: celery -A autocaller worker -Q celery -l INFO --concurrency=10

volumes:
 static_volume:

    


