# Generated by Django 3.2.23 on 2024-04-13 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_call_report'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_error',
            field=models.BooleanField(default=False),
        ),
    ]
