# Generated by Django 3.2.23 on 2024-05-28 09:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0008_report_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='create_by_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='report',
            name='call_queue',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
