# Generated by Django 3.2.23 on 2024-05-28 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_alter_call_end_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='percents',
            field=models.IntegerField(default=0),
        ),
    ]
