# Generated by Django 3.2.23 on 2024-05-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_remove_call_call_timeout'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='call_timeout',
            field=models.BooleanField(default=False),
        ),
    ]
