# Generated by Django 3.2.23 on 2024-05-31 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_call_abonent'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='phone_type',
            field=models.CharField(default=None, max_length=15, null=True),
        ),
    ]
