# Generated by Django 3.2.23 on 2024-05-31 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_call_phone_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='incorrect_input_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
