# Generated by Django 3.2.23 on 2024-06-04 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_alter_calllist_accept_combination'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='unchecked_abonents',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
