# Generated by Django 3.2.23 on 2024-04-08 20:15

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Abonent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=30, verbose_name='Фамилия')),
                ('patronymic', models.CharField(max_length=30, verbose_name='Отчетство')),
                ('work_phone_number', models.IntegerField(blank=True, null=True, verbose_name='Рабочий номер телефона')),
                ('mobile_phone_number', models.CharField(max_length=12, verbose_name='Мобильный номер телефона')),
                ('secondary_mobile_phone_number', models.CharField(blank=True, max_length=12, null=True, verbose_name='Дополнительный номер телефона')),
                ('department', models.CharField(choices=[('NUR', 'Ново-Уренгойское ЛПУМГ'), ('PURP', 'Пурпейское ЛПУМГ'), ('GUBK', 'Губкинское ЛПУМГ'), ('VING', 'Вынгапуровское ЛПУМГ'), ('ORTJ', 'Ортьягунское ЛПУМГ'), ('SRGT', 'Сургутское ЛПУМГ'), ('YBLK', 'Южно-Балыкское ЛПУМГ'), ('SAMS', 'Самсоновское ЛПУМГ'), ('DMNK', 'Демьянское ЛПУМГ'), ('TRTS', 'Туртасское ЛПУМГ'), ('TBL', 'Тобольское ЛПУМГ'), ('YARK', 'Ярковское ЛПУМГ'), ('BGND', 'Богандинское ЛПУМГ'), ('ISHM', 'Ишимское ЛПУМГ'), ('ADM', 'Администрация'), ('US', 'Управление связи'), ('UAVR', 'Управление аварийно-восстановительных работ'), ('UEZS', 'Управление по эксплуатации зданий и сооружений'), ('ITC', 'Инженерно-технический центр'), ('MSCH', 'Медико-санитарная часть'), ('UTT', 'Управление транспорта и специальной техники'), ('ALL', 'Все филиалы')], max_length=4, verbose_name='Филиал')),
            ],
        ),
        migrations.CreateModel(
            name='CallList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('list_name', models.CharField(max_length=20, verbose_name='Имя')),
                ('list_description', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('last_edit_time', models.DateTimeField(auto_now_add=True)),
                ('department', models.CharField(max_length=4)),
                ('main_phone', models.BooleanField(default=True)),
                ('second_phone', models.BooleanField(default=False)),
                ('work_phone', models.BooleanField(default=False)),
                ('accept_combination', models.IntegerField(default=555, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(999)])),
                ('abonents', models.ManyToManyField(to='main.Abonent')),
                ('last_edit_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SoundFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dir', models.CharField(max_length=100)),
                ('filename', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('in_progress', models.BooleanField(default=False)),
                ('list', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.calllist')),
            ],
        ),
        migrations.AddField(
            model_name='calllist',
            name='sound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.soundfile'),
        ),
        migrations.CreateModel(
            name='Call',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abonent_number', models.CharField(max_length=12, verbose_name='Номер телефона')),
                ('start_time', models.DateTimeField(auto_now_add=True)),
                ('call_rejected', models.BooleanField(default=False)),
                ('call_not_answered', models.BooleanField(default=False)),
                ('call_no_response', models.BooleanField(default=False)),
                ('call_answered', models.BooleanField(default=False)),
                ('user_input', models.CharField(max_length=3, null=True)),
                ('report', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.report')),
            ],
        ),
    ]
