# Generated by Django 3.2.23 on 2024-05-28 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_report_end_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='end_time',
            field=models.DateTimeField(null=True),
        ),
    ]
