# Generated by Django 3.2.23 on 2024-06-04 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0028_report_unchecked_abonents'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='call',
            name='percents',
        ),
    ]
