# Generated by Django 3.2.25 on 2024-11-13 19:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20241113_1839'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllist',
            name='pass_tries_number',
        ),
    ]
