# Generated by Django 3.2.25 on 2024-11-16 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0034_remove_calllist_pass_tries_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='abonent',
            name='patronymic',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Отчетство'),
        ),
    ]
