# Generated by Django 3.2.25 on 2024-11-20 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20241116_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='incorrect_pass_input_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AddField(
            model_name='call',
            name='user_pass_input',
            field=models.CharField(max_length=3, null=True),
        ),
    ]
