# Generated by Django 3.2.25 on 2024-11-20 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20241120_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='pass_confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
