# Generated by Django 3.2.23 on 2024-04-13 13:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_report_call_queue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='report',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='call', to='main.report'),
        ),
    ]
