# Generated by Django 3.2.23 on 2024-05-28 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_call_end_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='end_time',
            field=models.DateTimeField(default=None),
            preserve_default=False,
        ),
    ]
