# Generated by Django 3.2.23 on 2024-05-28 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_call_end_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='call',
            name='end_code',
            field=models.IntegerField(null=True),
        ),
    ]
