# Generated by Django 3.2.23 on 2024-05-31 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_call_incorrect_input_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
