# Generated by Django 3.2.23 on 2024-06-02 18:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_alter_calllist_sound'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllist',
            name='accept_combination',
            field=models.IntegerField(default=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
    ]
