# Generated by Django 3.2.23 on 2024-06-05 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_remove_call_percents'),
    ]

    operations = [
        migrations.AddField(
            model_name='call',
            name='ats_no_answer',
            field=models.BooleanField(default=False),
        ),
    ]
