# Generated by Django 3.2.25 on 2024-08-03 11:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0030_call_ats_no_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllist',
            name='tries_number',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(3)]),
        ),
    ]
