# Generated by Django 3.2.25 on 2024-08-31 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_calllist_tries_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonent',
            name='mobile_phone_number',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Мобильный номер телефона'),
        ),
    ]
