# Generated by Django 3.2.25 on 2026-03-10 10:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0037_call_pass_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllist',
            name='is_password',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='calllist',
            name='list_description',
            field=models.CharField(max_length=1000, verbose_name='Фамилия'),
        ),
        migrations.AlterField(
            model_name='calllist',
            name='list_name',
            field=models.CharField(max_length=50, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='calllist',
            name='password',
            field=models.IntegerField(default=None, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(9)]),
        ),
        migrations.AlterField(
            model_name='calllist',
            name='sound',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.soundfile'),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='filename',
            field=models.CharField(max_length=100),
        ),
    ]
