# Generated by Django 3.2.25 on 2026-03-10 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0038_auto_20260310_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllist',
            name='is_password',
            field=models.BooleanField(default=False),
        ),
    ]
