# Generated by Django 3.2.25 on 2026-03-17 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0039_alter_calllist_is_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllist',
            name='exclude_abonents',
            field=models.ManyToManyField(related_name='excluded_from_call_lists', to='main.Abonent'),
        ),
        migrations.AlterField(
            model_name='calllist',
            name='abonents',
            field=models.ManyToManyField(related_name='included_in_call_lists', to='main.Abonent'),
        ),
    ]
