# Generated by Django 3.2.25 on 2026-05-02 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0040_auto_20260317_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='soundfile',
            name='dir',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='soundfile',
            name='filename',
            field=models.CharField(max_length=300),
        ),
    ]
