[general]
static=yes
writeprotect=no
priorityjumping=no
autofallthrough=yes
clearglobalvars=no



[autocaller]
exten => call,1,Set(count=0)
exten => call,n,Set(pass_count=0)
exten => call,n,Wait(0.5)
exten => call,n,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/greetings)
exten => call,n,Wait(0.5)

; --- ПРОВЕРКА ФЛАГА ПАРОЛЯ ---
; Если is_pass равен 1, идем на ввод пароля, иначе сразу к сообщению (метка skip_pass)
exten => call,n,GotoIf($["${is_pass}" = "1"]?ask_pass:skip_pass)

; Блок работы с паролем
exten => call,n(ask_pass),Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/password)
exten => call,n,Wait(0.2)
exten => call,n(input_loop),Read(pass_input,,1)
exten => call,n,GotoIf($["${pass_input}" = "${pass}"]?skip_pass:pass_is_wrong,1)

; Блок воспроизведения сообщения
exten => call,n(skip_pass),Wait(0.2)
exten => call,n,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/invite)
exten => call,n,Wait(0.2)
exten => call,n(message_body),Playback(${data})
exten => call,n,Wait(0.5)
exten => call,n,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/2)
exten => call,n,Playback(/usr/share/asterisk/sounds/ru/digits/${code})
exten => call,n,Wait(0.2)
exten => call,n,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/3)
exten => call,n,Wait(0.3)
exten => call,n,Playback(/usr/share/asterisk/sounds/ru/beep)
exten => call,n,Wait(0.2)
exten => call,n,Goto(autocaller,message_process,1)

; Обработка ввода кода
exten => message_process,1,Read(user_input,,1)
exten => message_process,n,GotoIf($["${user_input}" = "${code}"]?accept,1:wrong_combination,1)

; Секция ошибки пароля
exten => pass_is_wrong,1,Set(pass_count=$[${pass_count} + 1])
exten => pass_is_wrong,n,GotoIf($["${pass_count}" >= "3"]?555,1)
exten => pass_is_wrong,n,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/wrong_password)
exten => pass_is_wrong,n,Wait(0.2)
exten => pass_is_wrong,n,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/try_again)
; Возвращаемся именно на шаг ввода, а не в начало
exten => pass_is_wrong,n,Goto(autocaller,call,input_loop)

exten => 555,1,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/wrong_password)
exten => 555,n,Wait(0.2)
exten => 555,n,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/denied)
exten => 555,n,Hangup()


exten => accept,1,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/Thanks)
exten => accept,n,Hangup()

; Ошибка кода подтверждения
exten => wrong_combination,1,Set(count=$[${count} + 1])
exten => wrong_combination,1,GotoIf($["${count}" >= "3"]?111,1)
exten => wrong_combination,n,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/Incorrect)
exten => wrong_combination,n,Goto(autocaller,call,message_body)

; Превышение попыток кода
exten => 111,1,Playback(/opt/autocaller/media/sounds/COMMON_SOUNDS/incorrect_hangup)
exten => 111,n,Set(count=$[${count} + 1])
exten => 111,n,Hangup()